// This file is generated by UI Designer (1, 3, 5, 5)
// DO NOT EDIT MANUALLY

#ifndef _MMI_ID_GPS_RES_H
#define _MMI_ID_GPS_RES_H

#define IDL_LAYOUT_GPS_MAIN                                0x00000001	
#define ID_LINEARLAYOUT_1                                  0x00000014	
#define IDS_STRING_RETURN                                  0x0000001e	
#define IDL_LISTITEM_GPS                                   0x0000001f	
#define IDC_TITLE_GPS                                      0x00000021	
#define IDC_LIST_GPS_DETAILS                               0x00000022	
#define IDC_STATIC_GPS_TITLE                               0x00000023	
#define IDS_STRING_GPS_LON                                 0x00000024	
#define IDS_STRING_GPS_LAT                                 0x00000025	
#define IDS_STRING_GPS_TIME                                0x00000026	
#define IDS_STRING_GPS_NUMER                               0x00000027	
#define IDC_STATIC_GPS_VALUE                               0x00000028	
#define IDS_APP_GPS                                        0x00000029	
#define IDS_STRING_GPS_NA                                  0x0000002a	
#define IDL_LISTITEM_AGPS                                  0x0000002c	
#define IDC_CHECKBOX_AGPS                                  0x0000002d	
#define IDS_STRING_AGPS_ENABLE                             0x0000002e	
#define IDS_STRING_OPEN                                    0x00000031	
#define IDS_STRING_CLOSE                                   0x00000032	
#define IDS_STRING_FAIL                                    0x00000033	
#define IDS_STRING_SEARCHING                               0x00000034	
#define IDC_STATIC_ENABLE_AGPS                             0x00000036	
#define IDS_STRING_STOP                                    0x00000037	
#define IDS_STRING_SEARCH                                  0x00000038	
#define IDS_STRING_PDP_FAIL                                0x00000039	
#define IDS_STRING_WAITING                                 0x0000003a	
#define IDS_STRING_QUERYING                                0x0000003b	
#define IDS_STRING_SUCCESS                                 0x0000003e	
#define IDS_STRING_DGPS                                    0x0000003f	
#define IDS_STRING_ESTIMATE                                0x00000040	
#define IDC_WIDGET_1                                       0x00000041	// not used, can be cleaned from UI Designer
#define IDL_WIDGET_GPS_INFO                                0x00000042	// not used, can be cleaned from UI Designer
#define IDC_PROGRESSBAR_1                                  0x00000043	// not used, can be cleaned from UI Designer
#define ID_LINEARLAYOUT_2                                  0x00000044	
#define IDL_WIDGET_GPS_SNR                                 0x00000045	// not used, can be cleaned from UI Designer
#define IDC_PROGRESSBAR_GPS_SNR                            0x00000046	// not used, can be cleaned from UI Designer
#define IDC_STATIC_SAT_NUM                                 0x00000047	
#define IDC_STATIC_SNR                                     0x00000048	// not used, can be cleaned from UI Designer
#define IDC_STATIC_GPS_ID                                  0x00000049	// not used, can be cleaned from UI Designer
#define IDC_WIDGET_SNR                                     0x0000004a	// not used, can be cleaned from UI Designer
#define IDC_WIDGET_SNR2                                    0x0000004b	// not used, can be cleaned from UI Designer
#define IDC_WIDGET_SNR1                                    0x0000004c	// not used, can be cleaned from UI Designer
#define IDC_WIDGET_SNR3                                    0x0000004d	// not used, can be cleaned from UI Designer
#define IDC_WIDGET_SNR4                                    0x0000004e	// not used, can be cleaned from UI Designer
#define IDC_WIDGET_SNR5                                    0x0000004f	// not used, can be cleaned from UI Designer
#define IDC_WIDGET_SNR6                                    0x00000050	// not used, can be cleaned from UI Designer
#define IDC_WIDGET_SNR7                                    0x00000051	// not used, can be cleaned from UI Designer
#define IDC_WIDGET_SNR8                                    0x00000052	// not used, can be cleaned from UI Designer
#define IDC_WIDGET_SNR9                                    0x00000053	// not used, can be cleaned from UI Designer
#define IDC_WIDGET_SNR10                                   0x00000054	// not used, can be cleaned from UI Designer
#define IDC_WIDGET_SNR11                                   0x00000055	// not used, can be cleaned from UI Designer
#define IDC_WIDGET_SNR12                                   0x00000056	// not used, can be cleaned from UI Designer
#define IDC_WIDGET_SNR13                                   0x00000057	// not used, can be cleaned from UI Designer
#define IDC_WIDGET_SNR14                                   0x00000058	// not used, can be cleaned from UI Designer
#define IDC_WIDGET_SNR15                                   0x00000059	// not used, can be cleaned from UI Designer
#define IDC_WIDGET_SNR16                                   0x0000005a	// not used, can be cleaned from UI Designer
#define IDC_WIDGET_SNR17                                   0x0000005b	// not used, can be cleaned from UI Designer
#define IDC_WIDGET_SNR18                                   0x0000005c	// not used, can be cleaned from UI Designer
#define IDC_WIDGET_SNR19                                   0x0000005d	// not used, can be cleaned from UI Designer
#define IDC_WIDGET_SNR20                                   0x0000005e	// not used, can be cleaned from UI Designer
#define IDC_WIDGET_SNR21                                   0x0000005f	// not used, can be cleaned from UI Designer
#define IDC_WIDGET_SNR22                                   0x00000060	// not used, can be cleaned from UI Designer
#define IDC_WIDGET_SNR23                                   0x00000061	// not used, can be cleaned from UI Designer
#define IDC_WIDGET_SNR24                                   0x00000062	// not used, can be cleaned from UI Designer
#define IDC_SLIDER_1                                       0x00000063	// not used, can be cleaned from UI Designer
#define IDC_SLIDER_GPS_SNR                                 0x00000064	// not used, can be cleaned from UI Designer
#define IDC_GRID_1                                         0x00000065	// not used, can be cleaned from UI Designer
#define IDC_WIDGET_GPS_SNR1                                0x00000066	// not used, can be cleaned from UI Designer
#define IDC_WIDGET_GPS_SNR2                                0x00000067	// not used, can be cleaned from UI Designer
#define IDC_WIDGET_GPS_SNR3                                0x00000068	// not used, can be cleaned from UI Designer
#define IDC_WIDGET_GPS_SNR4                                0x00000069	// not used, can be cleaned from UI Designer
#define IDC_WIDGET_GPS_SNR5                                0x0000006a	// not used, can be cleaned from UI Designer
#define IDC_WIDGET_GPS_SNR6                                0x0000006b	// not used, can be cleaned from UI Designer
#define IDC_WIDGET_GPS_SNR7                                0x0000006c	// not used, can be cleaned from UI Designer
#define IDC_WIDGET_GPS_SNR8                                0x0000006d	// not used, can be cleaned from UI Designer
#define IDC_WIDGET_GPS_SNR9                                0x0000006e	// not used, can be cleaned from UI Designer
#define IDC_WIDGET_GPS_SNR0                                0x0000006f	// not used, can be cleaned from UI Designer
#define IDC_WIDGET_GPS_SNR11                               0x00000070	// not used, can be cleaned from UI Designer
#define IDC_WIDGET_GPS_SNR12                               0x00000071	// not used, can be cleaned from UI Designer
#define IDC_WIDGET_GPS_SNR13                               0x00000072	// not used, can be cleaned from UI Designer
#define IDC_WIDGET_GPS_SNR14                               0x00000073	// not used, can be cleaned from UI Designer
#define IDC_WIDGET_GPS_SNR15                               0x00000074	// not used, can be cleaned from UI Designer
#define IDC_WIDGET_GPS_SNR16                               0x00000075	// not used, can be cleaned from UI Designer
#define IDC_WIDGET_GPS_SNR17                               0x00000076	// not used, can be cleaned from UI Designer
#define IDC_WIDGET_GPS_SNR18                               0x00000077	// not used, can be cleaned from UI Designer
#define IDC_WIDGET_GPS_SNR19                               0x00000078	// not used, can be cleaned from UI Designer
#define IDC_WIDGET_GPS_SNR20                               0x00000079	// not used, can be cleaned from UI Designer
#define IDC_WIDGET_GPS_SNR21                               0x0000007a	// not used, can be cleaned from UI Designer
#define IDC_WIDGET_GPS_SNR22                               0x0000007b	// not used, can be cleaned from UI Designer
#define IDC_WIDGET_GPS_SNR23                               0x0000007c	// not used, can be cleaned from UI Designer
#define IDC_WIDGET_GPS_SNR24                               0x0000007d	// not used, can be cleaned from UI Designer
#define IDS_STRING_GPS_ID                                  0x0000007e	
#define IDS_STRING_GPS_SNR                                 0x0000007f	
#define IDC_WIDGET_SNR_DISPLAY                             0x00000080	// not used, can be cleaned from UI Designer
#define ID_LINEARLAYOUT_3                                  0x00000081	
#define ID_LINEARLAYOUT_4                                  0x00000082	
#define IDS_STRING_SAT_ID                                  0x00000083	// not used, can be cleaned from UI Designer
#define IDC_STATIC_SAT_INFO                                0x00000084	
#define IDS_STRING_GPS_RUNNING                             0x00000086	
#define IDS_STRING_GPS_OPEN_FAILE                          0x00000088	

#endif
