#!/bin/sh

if [ -z $1 ]
then
  echo "parameter error!"
  exit
fi

#
username=$1
RepoName=$2
if [ -z "$3" ]
then
  description="Create a $RepoName at "$(date +%Y-%m-%d)
else
  description=$3
fi
echo "Name =" $username
echo "RepoName =" $RepoName
echo "Description =" $description
data="{\"name\":\""${RepoName}"\",\"description\":\""${description}"\"}"
echo "Data = "$data
curl -u $username https://api.github.com/user/repos -d "$data"
